####################################################
#
# Welcome to Tokyo Jekyll Theme
# Author Link : https://themeix.com/
# Version : v1.0.2
#
####################################################

# Site settings
title: "HUBSolutions"
email: "maarten.hubrechts@hotmail.com"
baseurl: ""
url: "url: "https://www.hubsolutions.be"
logo: /assets/images/header-brand.png
description: ""
keywords: "maarten hubrechts, data engineer, data architect, mechelen, responsive"
mailchimp: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=4784863884"
linkedin: "https://www.linkedin.com/in/maarten-hubrechts"
# facebook: https://facebook.com/themeix
# instagram: https://instagram.com/themeix
# twitter: https://twitter.com/themeix_com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  authors:
    output: true
    permalink: /author/:path/

feed:
  collections:
    posts:
      path: "/index.xml"
